//
// Created by dejan on 14.3.2016.
//

#ifndef SIPSTER_SDP_ENUMS_H
#define SIPSTER_SDP_ENUMS_H

typedef enum {
    SDP_HEADER_NONE = -1,
    SDP_HEADER_VERSION = 0,
    SDP_HEADER_ORIGIN,
    SDP_HEADER_SESSION_NAME,
    SDP_HEADER_SESSION_INFO,
    SDP_HEADER_DESC_URI,
    SDP_HEADER_EMAIL,
    SDP_HEADER_PHONE,
    SDP_HEADER_CONNECTION_INFO,
    SDP_HEADER_BANDWIDTH_INFO,
    SDP_HEADER_TIME_ACTIVE,
    SDP_HEADER_TIME_REPEAT,
    SDP_HEADER_TIME_ZONE,
    SDP_HEADER_ENCRYPTION_KEY,
    SDP_HEADER_ATTRIBUTE,
    SDP_HEADER_MEDIA
} SipsterSdpHeaderEnum;

typedef enum {
    SDP_MEDIA_NONE = -1,
    SDP_MEDIA_AUDIO = 0,
    SDP_MEDIA_VIDEO,
    SDP_MEDIA_TEXT,
    SDP_MEDIA_APP,
    SDP_MEDIA_MSG
} SipsterSdpMediaTypeEnum;

typedef enum {
    SDP_ATTRIBUTE_NONE = -1,
    SDP_ATTRIBUTE_CATEGORY = 0,
    SDP_ATTRIBUTE_KEYWORDS,
    SDP_ATTRIBUTE_TOOL,
    SDP_ATTRIBUTE_PTIME,
    SDP_ATTRIBUTE_MAXPTIME,
    SDP_ATTRIBUTE_RTPMAP,
    SDP_ATTRIBUTE_RECVONLY,
    SDP_ATTRIBUTE_SENDRECV,
    SDP_ATTRIBUTE_SENDONLY,
    SDP_ATTRIBUTE_INACTIVE,
    SDP_ATTRIBUTE_ORIENT,
    SDP_ATTRIBUTE_TYPE,
    SDP_ATTRIBUTE_CHARSET,
    SDP_ATTRIBUTE_SDPLANG,
    SDP_ATTRIBUTE_LANG,
    SDP_ATTRIBUTE_FRAMERATE,
    SDP_ATTRIBUTE_QUALITY,
    SDP_ATTRIBUTE_FMTP
} SipsterSdpAttributeEnum;

#endif //SIPSTER_SDP_ENUMS_H
